// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngutoyvtsgpxyqmkbpih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ndXRveXZ0c2dweHlxbWticGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Nzc2MTQsImV4cCI6MjA3MjI1MzYxNH0.6WS0Y2J5LSzqy0vRY8BXs0WEz1zUVGu2OVFzUCH2U6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});